// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rllpfnmhelrnombjyiuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsbHBmbm1oZWxybm9tYmp5aXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTY3OTAsImV4cCI6MjA3MTQ3Mjc5MH0.ppvwgBZGvWEU78u5Wr0ZVcqpsWYrWTDsVsHmkm4KjDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});